#!/bin/bash
aws_private_dns="10.99.0.2"
OS_chk=$(cat /etc/issue* | grep "Ubuntu 18.04")
if [[ $OS_chk != "" ]]; then
        sudo apt install resolvconf -y
        echo "nameserver ${aws_private_dns}" > /etc/resolvconf/resolv.conf.d/tail
        systemctl restart resolvconf
fi

mkdir -p /usr/local/bin/
mkdir -p /data


BASTION_SVR="getpub.zxz.local getpubext.zxz.kr"
for i in $BASTION_SVR ; do if [[ $(curl -Is $i --connect-timeout 5 | grep alive | wc -l) -eq 1 ]]; then echo -e "\033[1;32m$i ok\033[0m"; BASTION_ZZZ=$i ;fi ;done
if [[ $BASTION_ZZZ == "" ]]; then echo -e "\033[1;31m Bastion Server connect check! >> $BASTION_SVR \033[0m";exit 1;fi

cat << EOF > /usr/local/bin/get_public_key.sh
#!/bin/bash
BASTION_IP=$BASTION_ZZZ
server_ip=\$(curl -ksfL \${BASTION_IP}:998/ip.php)

for i in \$server_ip ; do
    curl -ksfL http://\$BASTION_IP/get_public_key.php?ip=\$i
done
EOF

chmod +x /usr/local/bin/get_public_key.sh
echo "AuthorizedKeysCommand /usr/local/bin/get_public_key.sh" >> /etc/ssh/sshd_config
echo "AuthorizedKeysCommandUser nobody" >> /etc/ssh/sshd_config
systemctl restart sshd
#service ssh restart
